import { loader } from 'fumadocs-core/source'
// @ts-ignore generated by fumadocs-mdx during Next builds
import { docs } from '../../.source/server'

export const source = loader(docs.toFumadocsSource(), {
  baseUrl: '/',
})
